import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

function Arrow({ diagonal = false }) { return <span aria-hidden="true" className="arrow">{diagonal ? '↗' : '→'}</span>; }
function App() {
  const [mode, setMode] = useState('register');
  const [photo, setPhoto] = useState(null);
  const [preview, setPreview] = useState('');
  const [name, setName] = useState('');
  const [age, setAge] = useState('');
  const [gender, setGender] = useState('');
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');
  const input = useRef();
  useEffect(() => { if (!photo) { setPreview(''); return; } const url = URL.createObjectURL(photo); setPreview(url); return () => URL.revokeObjectURL(url); }, [photo]);
  useEffect(() => {
    function paste(e) { if (mode !== 'verify') return; const file = [...(e.clipboardData?.files || [])].find(f => f.type.startsWith('image/')); if (file) { e.preventDefault(); setPhoto(file); setResult(null); setError(''); } }
    window.addEventListener('paste', paste); return () => window.removeEventListener('paste', paste);
  }, [mode]);
  function switchMode(next) { setMode(next); setPhoto(null); setResult(null); setError(''); if (input.current) input.current.value = ''; }
  function select(file) { if (!file) return; setPhoto(file); setResult(null); setError(''); }
  async function submit(e) {
    e.preventDefault(); if (!photo) { setError('Choose a photo first.'); return; }
    setBusy(true); setError(''); setResult(null);
    const form = new FormData(); form.append('image', photo);
    if (mode === 'register') { form.append('name', name); form.append('age', age); form.append('gender', gender); }
    try { const response = await fetch(`/api/${mode}`, { method: 'POST', body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Request failed.'); setResult(data); }
    catch (err) { setError(err.message || 'Something went wrong.'); }
    finally { setBusy(false); }
  }
  return <div className="site">
    <header className="topbar"><a className="brand" href="#top" aria-label="Tether home"><span className="brand-icon">⊞</span> tether<span className="brand-sub">/ registry</span></a><nav><a href="#playground">playground</a><a href="#how-it-works">how it works</a><a href="https://github.com/specterbuilds/tether-registry" target="_blank" rel="noreferrer">source <Arrow diagonal /></a></nav><span className="top-status"><i /> experimental v0.1</span></header>
    <main id="top"><section className="hero"><div className="hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="square" /> OPEN SOURCE / PHOTO PROVENANCE</div><h1>A photo carries<br /><em>a story.</em><span className="dot">_</span></h1><p>Give a photo a signed record. Then bring it back to see what the registry knows about it. No "AI detector" claims, just verifiable provenance.</p><a className="hero-link" href="#playground">try the playground <Arrow /></a></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-center"><div className="art-glyph">T<span>·</span></div></div><span className="art-label label-top">01 / REGISTER</span><span className="art-label label-bottom">02 / VERIFY</span><span className="art-cross cross-one">+</span><span className="art-cross cross-two">+</span></div></div><div className="hero-footer"><span>THE TETHER REGISTRY</span><span>ED25519 / SHA-256 / PERCEPTUAL MATCHING</span><span>SCROLL TO EXPLORE ↓</span></div></section>
    <section id="playground" className="playground"><div className="section-head"><span className="kicker">THE PLAYGROUND / 01</span><h2>See the link<br /><em>for yourself.</em></h2><p>Register a sample photo, download it, then upload or paste it back. This demo is public: use made-up details, not personal data.</p></div><div className="workspace"><div className="tabs" role="tablist"><button role="tab" aria-selected={mode === 'register'} className={mode === 'register' ? 'active' : ''} onClick={() => switchMode('register')}>01 <span>Register a photo</span></button><button role="tab" aria-selected={mode === 'verify'} className={mode === 'verify' ? 'active' : ''} onClick={() => switchMode('verify')}>02 <span>Verify a photo</span></button></div><div className="work-body"><div className="work-intro"><span className="micro">{mode === 'register' ? 'ISSUE A RECORD' : 'LOOK UP A RECORD'}</span><h3>{mode === 'register' ? 'Start with a photo.' : 'Bring it back.'}</h3><p>{mode === 'register' ? 'Add sample details and an image. The registry signs a record bound to the image, then gives you a PNG to download.' : 'Upload or paste the downloaded PNG. If its bytes match a trusted registry record, the signed details come back.'}</p><div className="work-index">{mode === 'register' ? '01 — 02' : '02 — 02'} <span>↗</span></div></div><form onSubmit={submit} className="form-panel"><div className="form-title"><span>{mode === 'register' ? 'NEW ATTESTATION' : 'LOOKUP'}</span><span>PNG / JPEG / WEBP · MAX 8 MB</span></div>{mode === 'register' && <div className="fields"><label>NAME<input required maxLength="80" placeholder="e.g. Alex Sample" value={name} onChange={e => setName(e.target.value)} /></label><div className="field-row"><label>AGE<input required type="number" min="18" max="120" placeholder="e.g. 28" value={age} onChange={e => setAge(e.target.value)} /></label><label>GENDER<input required maxLength="40" placeholder="e.g. non-binary" value={gender} onChange={e => setGender(e.target.value)} /></label></div></div>}
      <div className={'dropzone ' + (photo ? 'has-photo' : '')} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); select(e.dataTransfer.files[0]); }} onClick={() => input.current?.click()} role="button" tabIndex={0} onKeyDown={e => { if (e.key === 'Enter') input.current?.click(); }}><input ref={input} type="file" accept="image/png,image/jpeg,image/webp" onChange={e => select(e.target.files[0])} hidden />{preview ? <><img src={preview} alt="Selected photo preview" /><div className="drop-text"><span>{photo?.name || 'pasted image'}</span><small>click to replace</small></div></> : <><span className="upload-icon">↥</span><strong>{mode === 'verify' ? 'Drop, choose or paste your photo' : 'Drop or choose a photo'}</strong><small>{mode === 'verify' ? 'Ctrl/⌘ + V works anywhere on this page' : 'Your photo becomes a normalized PNG'}</small></>}</div><button className="submit" disabled={busy} type="submit">{busy ? 'Working…' : mode === 'register' ? 'Sign & register photo' : 'Verify this photo'} <Arrow /></button>{error && <div className="error" role="alert">{error}</div>}
      {result && mode === 'register' && <div className="result" role="status"><span className="result-kicker">✓ RECORD CREATED</span><h4>Photo registered.</h4><p>The same PNG is ready to download. Bring it back in the Verify tab to recover its signed record.</p><a className="download" href={result.downloadUrl} download="tethered-photo.png">Download tethered photo ↓</a><div className="result-id">MANIFEST ID <code>{result.manifestId}</code></div></div>}
      {result && mode === 'verify' && <div className="result" role="status"><span className="result-kicker">{result.status === 'verified' ? '✓ SIGNATURE VALID · EXACT MATCH' : 'NO VERIFIED DETAILS'}</span><h4>{result.status === 'verified' ? 'Record found.' : result.status === 'similar' ? 'Similar photo found.' : 'No trusted record.'}</h4>{result.status === 'verified' ? <><dl><div><dt>NAME</dt><dd>{result.details?.name}</dd></div><div><dt>AGE</dt><dd>{result.details?.age}</dd></div><div><dt>GENDER</dt><dd>{result.details?.gender}</dd></div><div><dt>ISSUED BY</dt><dd>{result.issuer}</dd></div></dl><div className="result-id">MANIFEST ID <code>{result.manifestId}</code></div></> : <p>{result.message || 'This image was not registered here. Register it first, then verify the downloaded PNG.'}</p>}</div>}
      </form></div></div></section>
    <section id="how-it-works" className="how"><div className="section-head"><span className="kicker">UNDER THE HOOD / 02</span><h2>Not magic.<br /><em>A signed record.</em></h2><p>The photo does not contain encrypted identity. The server keeps a signed manifest and finds it again by image hash.</p></div><div className="steps"><article><span className="step-num">01 / PREPARE</span><div className="step-mark">⌗</div><h3>Normalize</h3><p>Upload PNG, JPEG, or WebP. The server rotates and converts it to PNG so the demo works with the SDK's current PNG support.</p></article><article><span className="step-num">02 / ATTEST</span><div className="step-mark">✳</div><h3>Sign</h3><p>Tether binds the image hash and claims to an Ed25519-signed manifest, stored in a local SQLite registry.</p></article><article><span className="step-num">03 / RECOVER</span><div className="step-mark">↗</div><h3>Verify</h3><p>Upload the downloaded PNG. Exact bytes plus a valid trusted signature bring back the sample details.</p></article></div><div className="notice"><span>AN IMPORTANT DISTINCTION</span><p>This is provenance, not encryption. A watermark embedder is not implemented in the SDK yet, so stripping or changing pixels may prevent exact recovery. Similar matches never reveal profile details in this demo. Do not enter real personal information.</p></div></section></main><footer><div><span className="brand"><span className="brand-icon">⊞</span> tether<span className="brand-sub">/ registry</span></span><p>A small place to see photo provenance work.</p></div><div className="footer-links"><a href="https://github.com/specterbuilds/tether-registry">registry source ↗</a><a href="https://github.com/specterbuilds/tether">tether sdk ↗</a></div><small>EXPERIMENTAL · NOT FOR REAL IDENTITY VERIFICATION</small></footer></div>;
}
createRoot(document.getElementById('root')).render(<App />);
